[display]
framebuffer="/dev/fb0"
layout = { horizontal = 2, vertical = 2 }

[[sources]]
description="Basement"
rtsp="rtsp://192.168.1.1:7447/lU7RqYAF3W9ZborZ"

[[sources]]
description="Backdoor"
rtsp="rtsp://192.168.1.1:7447/IjIY1LIA3w5k2XW3"

[[sources]]
description="Doorbell"
rtsp="rtsp://192.168.1.1:7447/XzM3XEhXCY2jNB8G"

[[sources]]
description=""
image="cat-3.png"
