[display]
framebuffer="/dev/fb0"
layout = { horizontal = 2, vertical = 2 }
time="%d %b - %H:%M"

[[sources]]
description="Basement"
rtsp="rtsp://192.168.1.1:7447/FP6m5n8xk03pNxvP"
scale="crop"

[[sources]]
description="Backdoor"
rtsp="rtsp://192.168.1.1:7447/5uGkJWowQg3ZA5xK"
scale="crop"

[[sources]]
description="Cat feeder"
rtsp="rtsp://192.168.1.1:7447/euoO4WFtCtzwkknU"
scale="crop"

[[sources]]
description="Doorbell"
rtsp="rtsp://192.168.1.1:7447/2CXbkmWvaQoFZKoI"
scale="crop"

# [[sources]]
# description=""
# image="placeholder.png"
# width=640
# height=640