[display]
framebuffer="/dev/fb0"
layout = { horizontal = 2, vertical = 2 }
time="%d %b - %H:%M"

[[sources]]
description="Basement"
rtsp="rtsp://192.168.1.1:7447/lU7RqYAF3W9ZborZ"
scale="crop"

[[sources]]
description="Backdoor"
rtsp="rtsp://192.168.1.1:7447/IjIY1LIA3w5k2XW3"
scale="crop"

[[sources]]
description="Cat feeder"
rtsp="rtsp://192.168.1.1:7447/h3ykz5s09oGhWYXM"
scale="crop"

[[sources]]
description="Doorbell"
rtsp="rtsp://192.168.1.1:7447/fbsLGYIOao1Q1wGO"
scale="fit"

#description=""
#image="placeholder.png"
#width=640
#height=640
